import streamlit as st

st.error('This is an error message')
st.warning('This is a warning message')
st.info('This is an info message')
st.success('This is a success message')
st.exception('This is an exception message')
st.help('This is a help message')
st.write('This is a write message')
st.code('This is a code message')
st.json('{"name": "John", "age": 30, "city": "New York"}')
st.markdown('This is a markdown message')
st.caption('This is a caption message')
st.latex(r'\frac{1}{2} \cdot \sqrt{3} = \frac{\sqrt{3}}{2}')
st.balloons()
st.snow()
st.toast('This is a toast message', duration=5)
st.toast('This is a toast message', duration=5, icon='✅', color='green')
st.toast('This is a toast message', duration=5, icon='⚠️', color='yellow')
st.toast('This is a toast message', duration=5, icon='❌', color='red')